### ISSUE TITLE
ctrl+b runs, ctrl+shift+b compiles

### ISSUE THREAD

**Issue by nietsme** [ahkscript/SublimeAutoHotkey#11]
I have the default Sublime keybindings, but it will run when pressing ctrl+b & compile when ctrl+shift+b, i don't know why?!

the menus "Tools > AutoHotkey - Run" & "Tools > AutoHotkey - Compile" works well.

**Comment by robertcollier4** [comment]
This is the intended behavior. Ctrl+B has been mapped to "Run" since this is much more often used. See README.
