### ISSUE TITLE
Reloading current file?

### ISSUE THREAD

**Issue by fredrikpaues** [ahkscript/SublimeAutoHotkey#19]
Is there a way to reload the current AHK script directly from Sublime? If not, would you consider adding it?

**Comment by G33kDude** [comment]
Wouldn't just running the script do that if `#SingleInstance, Force` is on?

**Comment by fredrikpaues** [comment]
Yes, it would. But does the package provide a way to do just that from within Sublime? I can't seem to find it.



Mvh Fredrik
(Skickat från mobilen)

**Comment by denolfe** [comment]
Yes, it is in the [Advanced Configuration](https://github.com/ahkscript/SublimeAutoHotkey#advanced-configuration) of the readme.  `Ctrl+Shift+P` -> `Autohotkey Run`

**Comment by fredrikpaues** [comment]
Ah, my bad! Thanks a bunch!

**Comment by denolfe** [comment]
I will say that I use my own script instead of the built-in build system. Here it is.

	SetTitleMatchMode, RegEx

	#IfWinActive .*ahk .*
	+F5::
			Send ^s
			WinGetTitle, Title, A
			If InStr(Title, ".ahk")
			Run % Substr(Title, RegExMatch(Title, "P).*.ahk", matchlength), matchlength)
			Return

**Comment by fredrikpaues** [comment]
I had forgotten to change the `AutoHotKeyExePath` and `Ahk2ExePath` paths in the settings. Once I did that everything worked just fine.
