### ISSUE TITLE
Multiple paths for AHK executables

### ISSUE THREAD

**Issue by fredrikpaues** [ahkscript/SublimeAutoHotkey#20]
It doesn't seem to be possible to enter multiple paths for `AutoHotKeyExePath` and `Ahk2ExePath`, like so:

    {
        "AutoHotKeyExePath": {
        	"default": ["C:\\Program Files (x86)\\AutoHotkey\\AutoHotkey.exe", "C:\\Program Files\\AutoHotkey\\AutoHotkey.exe"]
        },
        "Ahk2ExePath": {
        	"default": ["C:\\Program Files (x86)\\AutoHotkey\\Compiler\\Ahk2Exe.exe", "C:\\Program Files\\AutoHotkey\\Compiler\\Ahk2Exe.exe"]
        }
    }

Am I just doing it wrong? Or could support for this be added?

The reason I want this is that I'm using the [Sublime Package Syncing](https://github.com/csch0/SublimeText-Package-Syncing) to sync my Sublime settings between my home computer and my work computer and the executables are saved under different paths on the two computers.

**Comment by robertcollier4** [comment]
Good idea, implemented.

**Comment by fredrikpaues** [comment]
Nice! Thank you!
