### ISSUE TITLE
Reload/build script very unreliable

### ISSUE THREAD

**Issue by fredrikpaues** [ahkscript/SublimeAutoHotkey#21]
When I hit `Ctrl+B` to build/reload my script, nothing happens.

I'm using Windows 8.1 and Sublime build 3083 and I have changed the path to Autohotkey.exe in my user settings.

**Comment by Rosseiro** [comment]
Check whether Sublime Text is running with the same privileges as AutoHotKey. If AutoHotKey.exe is set to run as admin and ST is not, then the latter will struggle while trying to execute the build command.

**Comment by fredrikpaues** [comment]
ST and AHK have the same privileges -- they are run by the user Fredrik (that's me), and not as admin.

**Comment by Rosseiro** [comment]
Double-check if the backslashes in the path you inserted are escaped. Like C:\\Program Files\\Sublime Text 3 and not C:\Program Files\Sublime Text 3. The same for the AutoHotKey path. If not, try checking if the AHK package is really installed. If you use Package Control, go to List Packages.

**Comment by Rosseiro** [comment]
Try removing the package completely and installing it over. First, using package control, check again the privileges and the escaped backslashes and test. If unsuccessful, try removing the package, then search for remaining files inside the C:\Users\yourname\AppData\Roaming\Sublime Text 2\Installed Packages files and try downloading manually, moving the files to that folder to install the package.

**Comment by Rosseiro** [comment]
Another thing that has just occurred to me is that, although I might be very wrong, Sublime doesn't have permission to call another application under the Program Files folder, which happens to be a system directory. By hitting Ctrl+B to use the Build command, you would have ST call AutoHotKey.exe. I think this *might* be still a permission issue.

**Comment by robertcollier4** [comment]
Push <kbd>ctrl+`</kbd> to load the "Console" - it should show you some kind of error message there indicating what the problem is.

**Comment by fredrikpaues** [comment]
I removed the paths from my user settings and now I can't seem to replicate the problem anymore. The script reloads perfectly on every `Ctrl+B`. Thank you!
