### ISSUE TITLE
Autocompletition doesn't Work Properly

### ISSUE THREAD

**Issue by 4StarGeneral** [ahkscript/SublimeAutoHotkey#25]
After I entered the first command, the autocompletition doesn't work anymore...

**Comment by aviaryan** [comment]
I too noticed that Autocomplete is reacting a bit slow. To get Autocomplete for ControlSetText, I had to type till `ControlS` for the list to show.

**Comment by denolfe** [comment]
There are a few quirks I've noticed as well. `Loop` vs `loop` for example.

**Comment by robertcollier4** [comment]
I often disable the language-specific completions (i.e. rename "AutoHotkey.sublime-completions" to "AutoHotkey.sublime-completions.disabled").

This then allows for the popup AutoComplete suggest to recommend local variable names instead of being overburdened by all the AutoHotkey commands.
