### ISSUE TITLE
Should I include a Sublime Text 3 only plugin in this distribution

### ISSUE THREAD

**Issue by aviaryan** [ahkscript/SublimeAutoHotkey#26]
Hi.
I was thinking of making a plugin that will display tooltip help for a command, directive or a function. It works when you press the required key combo while the caret is on the ahk keyword. 
To display tips, it will make use of show_popup() function which is available only in ST 3.
Should I proceed ?

@robertcollier4 @Ragnar-F @joedf 

A prototype looks like this - 
![tthelp](https://cloud.githubusercontent.com/assets/4047597/11115261/47a31710-8950-11e5-8325-2f98e5dfc504.png)

It refers to the .sublime-completions file for syntax. I will have to add a `.no-sublime-package` file in this repository for this to work.

**Comment by jshall** [comment]
I think that sounds like a great feature.

**Comment by aviaryan** [comment]
I installed the package in ST 2 and it ran without errors so I guess I will add the feature to this package.
In ST 2, the plugin displays a status message stating the ST version is not supported.

**Comment by joedf** [comment]
Very nice! :+1:

**Comment by robertcollier4** [comment]
Nice. Following forum posts confirms show_popup() is available in Dev Build 3070 and later:
https://www.sublimetext.com/forum/viewtopic.php?f=2&t=17583

**Comment by joedf** [comment]
Nice.
