### ISSUE TITLE
version 1.5.0 with syntax error ?

### ISSUE THREAD

**Issue by Luxvero** [ahkscript/SublimeAutoHotkey#27]
when i try to run a script from sublime an error message is shown about unexpected comma before bracket

so manually inspecting the file

file: AutoHotkey.sublime-build
lines 8 and 9 follow:
```
   "target": "ahkcompile",
}
```

i tried with a fresh sublime 2.0.2 (portable) and upon installing package control and then SublimeAutoHotkey, there is the error.

by the way, despite fixing that,  in menu Tools > "AutoHotkey - Run"  and the other 2 options are greyed out. The whole ahk build system stopped working several days ago but i didnt bother, so i  dont know if it was v1.4.0, v1.4.1, or v1.5.0 that broke it, but i gather this is a matter for a new issue after i make sure its not some detail on my end.

**Comment by robertcollier4** [comment]
Thanks for reporting this. The problem is that although SublimeText3 ignores and allows it, SublimeText2 does not allow for trailing commas at the end of a JSON list.

https://github.com/ahkscript/SublimeAutoHotkey/commit/dec847fa90021e9a16d7bdc49aeea15478597d7d
