### ISSUE TITLE
How can i run my script?

### ISSUE THREAD

**Issue by STYY** [ahkscript/SublimeAutoHotkey#30]
Hi,

"Ctrl+B will run the current file (with AutoHotkey.exe)" is not working for me.
It always compiles the .ahk to an .exe but it won't run it.

what can i do?

**Comment by aviaryan** [comment]
Try Ctrl+Shift+B then.

**Comment by STYY** [comment]
tried it also it just says:
"Successfully compiled: 
[Finished in 0.1s]"

But the script will not started..

**Comment by aviaryan** [comment]
Which Sublime Text version are you on ? In ST 3, you press Ctrl+Shift+B, the build options come up and you select "AutoHotkey" to run the script. 
Also make sure you are running the latest version of AutoHotkey package. Ctrl-Shift-P, then "Package Control Upgrade Package" -> AutoHotkey

**Comment by STYY** [comment]
I am pretty sure, ive installed Sublime Text 3. The install folder is also named in Sublime Text 3. Checked ST3 for updates, no aviable.

Ctrl+Shift+P -> Package Control Upgrade Package = "---------------------------
Sublime Text
---------------------------
Package Control

There are no packages ready for upgrade
---------------------------
OK   
---------------------------
"

When i press Ctrl+Shift+B, i can choose "Autohotkey" and "Autohotkey - Run", both are compiling the script, but won't run it.

**Comment by lsj8924** [comment]
I also have the same problem. I don't  konw how to deal with it.

**Comment by lw1990** [comment]
This problem is caused by not having sublimetext running as administrator.

**Comment by dreamcat4** [comment]
The command name is `ahkrun`. Source: https://stackoverflow.com/a/18882121

For sublime 3, you need to open up `Preferences --> Key Bindings` and append the following key binding to the right panel (user keybindings file):

```json
[
	{ "keys": ["ctrl+shift+r"], "command": "ahkrun" }	
]
```

or something similar. Whatever your preferred keybinging is. Custom user defined keybindings aught to override the default system and package level keybindings. So you can override `ctrl+shift+b` instead if you prefer.

Valid json: Assuming you are brand new to sublime settings files, it has to be valid formed json data. So each keybinding array items which are not the last item in the list need to have a comma between them, for example:

```json
[
	{ "keys": ["ctrl+shift+a"], "command": "first_command" },
	{ "keys": ["ctrl+shift+b"], "command": "ahkrun" },
	{ "keys": ["ctrl+shift+c"], "command": "last_command_no_comma" }	
]
```
