### ISSUE TITLE
inline comment

### ISSUE THREAD

**Issue by kuntau** [ahkscript/SublimeAutoHotkey#34]
inline comment should be detected as comment and not syntax highlighted

**Comment by multimentha** [comment]
Mostly inline comments are not highlighted as such, sometimes it works though:
![screenshot - 20 06 2016 01_18_18](https://cloud.githubusercontent.com/assets/13744422/16180447/2820e9f2-3685-11e6-859c-50b117136933.png)

My wild guess would be that the regular expression groups for inline comments inside of [AutoHotkey.tmLanguage](../blob/master/AutoHotkey.tmLanguage) need to be updated.

**Comment by JTB3** [comment]
I concur, inline comments are now broken with the latest release. Here is an example...

![hotkeyremap ahk_ _-_sublime_text_2016-07-20_12 40 06](https://cloud.githubusercontent.com/assets/634825/17000376/19f46d7c-4e77-11e6-8e40-1dd270522dc0.png)

Please fix/update this!

**Comment by JTB3** [comment]
I can confirm now that that the problematic inline comment issue was introduced with version 1.7.1
**As a workaround to this issue**, I just uninstalled v1.7.1 via package control and manually reinstalled v1.7.0 via the zip file.  All is well now!  See example...

![hotkeyremap ahk_ _-_sublime_text_2016-07-20_13 12 29](https://cloud.githubusercontent.com/assets/634825/17001440/d975c408-4e7b-11e6-8946-16c9a980e2b2.png)

**Comment by omarabdelsalam** [comment]
Also having the same issue. Please fix

**Comment by PeterAdrianoDeBiase** [comment]
+1. I have been trying to figure out how to update the [AutoHotkey.tmLanguage](https://github.com/ahkscript/SublimeAutoHotkey/blob/master/AutoHotkey.tmLanguage) file to fix this bug but have so far been unsuccessful. Any help would be much appreciated.

![default](https://cloud.githubusercontent.com/assets/15940251/19219955/8bb80d1c-8dd6-11e6-8118-4493eca022fa.png)

**Comment by aviaryan** [comment]
Have you tried changing [L29](https://github.com/ahkscript/SublimeAutoHotkey/blob/master/AutoHotkey.tmLanguage#L29) from `<string>^\s*(;)(.*)$</string>` to `<string>\s*(;)(.*)$</string>`

**Comment by PeterAdrianoDeBiase** [comment]
Many thanks aviaryan! I can confirm this change works:

![default](https://cloud.githubusercontent.com/assets/15940251/19220376/b68486f6-8de0-11e6-82b2-9842b7f1bdc7.png)

Until this change gets added to the official release, I am following the instructions [here](http://www.sublimetext.com/docs/3/packages.html) to override the default AutoHotkey.tmLanguage file with a version of the AutoHotkey.tmLanguage file updated as per aviaryan's suggestion.

**Comment by whismerhill** [comment]
many thanks to all the contributors, I did the change too, I don't see a pull request regarding this though ???

**Comment by vith** [comment]
This pull request looks related: https://github.com/ahkscript/SublimeAutoHotkey/pull/39

**Comment by vith** [comment]
The regex in https://github.com/ahkscript/SublimeAutoHotkey/pull/39 is subtly more correct than the one previously suggested here. The difference is that a line such as `Send, hello;world` does not effectively contain a comment.

**Comment by omarabdelsalam** [comment]
> Have you tried changing [L29](https://github.com/ahkscript/SublimeAutoHotkey/blob/master/AutoHotkey.tmLanguage#L29) from `<string>^\s*(;)(.*)$</string>` to `<string>\s*(;)(.*)$</string>`

@aviaryan  https://github.com/ahkscript/SublimeAutoHotkey/issues/34#issuecomment-252483028
Actually it should be as @tmplinshi  https://github.com/ahkscript/SublimeAutoHotkey/pull/39 suggestion.
You should replace to `<string>(^\s*|\s+)(;)(.*)$</string>` instead in order not to violate AHK [commenting rules](https://autohotkey.com/docs/commands/_CommentFlag.htm).
Please confirm @tmplinshi's pull request.

**Comment by aviaryan** [comment]
@omarabdelsalam Yes. You are right. Will merge it and update on Package repository.
