### ISSUE TITLE
Allow download/install on Linux (OSX?)

### ISSUE THREAD

**Issue by jimbo1qaz** [ahkscript/SublimeAutoHotkey#36]
I'm running AutoHotkey under Wine to automate some Wine programs. However this package is marked Windows-only. Can you edit package-metadata.json (or Package Control settings) to allow installation under all platforms?

I think Package Control is deleting my package whenever I try to copy it from Windows. User-hostile action?

It seems that platform `*` works.

**Comment by jimbo1qaz** [comment]
I tried manually changing the platform, but Package Control is still deleting the package whenever I try to use it. Probably caching or something. Package Control is evil.

**Comment by G33kDude** [comment]
The package includes a windows-only python script `ahkexec.py`, which is probably why it's not marked as cross platform already. I'm not familiar with the intricacies of sublime packages though, so maybe there's a solution that makes more sense than marking the full package as cross platform when it contains non cross platform components.

**Comment by robertcollier4** [comment]
This is done as of https://github.com/wbond/package_control_channel/commit/e46f59d73e488cc1cb09c29b1d3ce031d1bc15c2
