### ISSUE TITLE
Ctrl+B doesn't support file path that containing Chinese characters

### ISSUE THREAD

**Issue by tmplinshi** [ahkscript/SublimeAutoHotkey#38]
**Console Log**:
> Running D:\code\AutoHotkey\AutoHotkey.exe /ErrorStdOut D:\Desktop\测试.ahk
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 337, in run_
  File ".\exec.py", line 154, in run
  File ".\exec.py", line 48, in __init__
  File ".\subprocess.py", line 633, in __init__
  File ".\subprocess.py", line 842, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode characters in position 58-59: ordinal not in range(128)

Tested on Sublime Text 2, Windows 10 x64.

**Comment by robertcollier4** [comment]
Curious, does this same file work with Ctrl+Shift+B Ahk2Exe? Ctrl+Shift+B is not using "file_regex" argument of run_command(exec). Perhaps if we remove the "file_regex" it would work then?

```
self.window.run_command("exec", {"cmd": cmd, "file_regex": regex})
self.window.run_command("exec", {"cmd": cmd})
```

**Comment by joedf** [comment]
What's the status of this issue?

**Comment by tmplinshi** [comment]
Ctrl+Shift+B has the same issue on Sublime Text 2.

Sublime Text 3 doesn't have this issue.
