### ISSUE TITLE
[Feature request] AutoHotkey output panel hide

### ISSUE THREAD

**Issue by Kristinita** [ahkscript/SublimeAutoHotkey#40]
### Request

It would be nice, if you add opportunity hide AutoHotkey panel, if script run was successfully.

### Justification

I need hide panel manually, I spend time on it.

### Steps for reproduce

I install AutoHotkey → I install and configure [SublimeAutoHotkey](https://github.com/ahkscript/SublimeAutoHotkey) → I create any `ahk` file, for example:

```autohotkey
:R*:/Sasha::Sasha is amazing!
```

<kbd>Ctrl+Shift+P</kbd> → `AutoHotkey - Run` → if script successful run, output panel not hide for me.

![Actual behavior](http://i.imgur.com/5UnrSsM.gif)

### Possible solution

See [answer](https://github.com/albertosantini/sublimetext-buildnext/issues/10#issuecomment-261698910) of BuildNext plugin owner.

```python
        exit_code = proc.exit_code()
        errors_len = len(self.output_view.find_all_results())

        if (exit_code != None and exit_code != 0) or errors_len > 0:
            self.window.run_command("show_panel", {"panel": "output.exec"})
        else:
            self.window.run_command("hide_panel", {"panel": "output.exec"})
```

Thanks.

**Comment by davebrny** [comment]
i would like to see this added as well.   
in the meantime, you could use this if you dont mind using a hotkey instead of the command palette:


```
#ifWinActive ahk_class PX_WINDOW_CLASS

^!r::
winMenuSelectItem, ahk_class PX_WINDOW_CLASS, , Tools, Autohotkey - Run
send {esc}
return

#ifWinActive
```
