### ISSUE TITLE
syntax error when using :: 

### ISSUE THREAD

**Issue by davebrny** [ahkscript/SublimeAutoHotkey#41]
i noticed this syntax error a while back, i think it was in version 1.7.0 as far as i remember but im not sure how far it goes back. 

![screenshot 2016-12-01](https://cloud.githubusercontent.com/assets/23744254/20802600/72b43060-b7e4-11e6-91ed-545f64717ad1.jpg)

**Comment by robertcollier4** [comment]
Todo: change hotkeyline.ahk to incorporate "negative look ahead" such as:

```
^\s(?!::)*(.+)(::)
 ```

**Comment by robertcollier4** [comment]
FIxed by PR #53
