### ISSUE TITLE
Interactive Debugging

### ISSUE THREAD

**Issue by lipkau** [ahkscript/SublimeAutoHotkey#42]
I would like to be able to use the AHK's support for DBGp.
However, I was only able to find [one forum entry](https://autohotkey.com/boards/viewtopic.php?t=10389) asking for help without replies.

I anyone using this (or the Xdebug Client package) for AHK coding in sublime?

**Comment by robertcollier4** [comment]
This is better discussed on the forum rather than in a issue.
