### ISSUE TITLE
fix for function regex matching if statements

### ISSUE THREAD

**Issue by KuroiLight** [ahkscript/SublimeAutoHotkey#46]
_Posting this here for anyone using this._
**Problem:**
currently the function regex matches if statements too if using OTB style causing bad code highlighting on everything in that line.
**Fix:**
change regex on https://github.com/ahkscript/SublimeAutoHotkey/blob/dc20ea3b615d902fc43045c1073353af5f9e0edf/AutoHotkey.tmLanguage#L78
to `^\s*((?!\bif\b)\w+)(\()(.*)(\))\s*({)\s*(;?.*)$` seems to fix it, this could be expanded to include other statements (like _while_).

**Comment by Ack0** [comment]
@KuroiLight Thanks!
What do you think about doing a pull request?
