### ISSUE TITLE
Wrong block comment highlight

### ISSUE THREAD

**Issue by myfonj** [ahkscript/SublimeAutoHotkey#47]
> `/*` and `*/` symbols can be used to comment out an entire section, but _only if the symbols appear at the beginning of a line_ (…)
https://autohotkey.com/docs/Language.htm#comments
It does not correspond with defined syntax:
https://github.com/ahkscript/SublimeAutoHotkey/blob/dc20ea3b615d902fc43045c1073353af5f9e0edf/AutoHotkey.tmLanguage#L34-L41
supposedly yielding:
![ahk-comment-highlight-bad 4b16c](https://user-images.githubusercontent.com/1761395/34482244-053011ce-efb7-11e7-8752-f59fd6399596.png)
Correct highlight should be
![ahk-comment-highlight-good 4b16c](https://user-images.githubusercontent.com/1761395/34482245-054fa37c-efb7-11e7-8a01-ef83fd7e80db.png)

---

Ran into this in VSCode port ( stef-levesque/vscode-autohotkey#9 ) and after fixing noticed it is derived from here; it seems most (other derived) syntax definitions for AHK exhibits the same bug.

**Comment by Kotsuha** [comment]
I recently ran into this as well, just a little differently. Sublime Text has a default key binding <kbd>ctrl+shift+/</kbd> for toggling block comment. Currently with this package, it produces comment like this:
```
/*#!r::
	Tester.ReloadThisScript()
Return*/
```
I feel it would be nice if the `*/` can be automatically put in a new line:
```
/*#!r::
	Tester.ReloadThisScript()
Return
*/
```
