### ISSUE TITLE
InputBox completion suggestion

### ISSUE THREAD

**Issue by HenriAugusto** [ahkscript/SublimeAutoHotkey#55]
Hey, great package! :)

I've noticed the InputBox syntax completion is missing the _Default_ parameter.

Current Syntax [from the docs](https://www.autohotkey.com/docs/commands/InputBox.htm) 

`InputBox, OutputVar [, Title, Prompt, HIDE, Width, Height, X, Y, Font, Timeout, Default]`

Current completion the package is suggesting

`InputBox, OutputVar [, Title, Prompt, HIDE, Width, Height, X, Y, Font, Timeout`

**Comment by joedf** [comment]
Fixed. 👍
