### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Notuses** [ahkscript/SublimeAutoHotkey#56]
Simply does not work. I tried to install both ways without given the highlighting option in sublime text 3 newest version 2019-10-17.

When will there be a fix?

**Comment by robertcollier4** [comment]
what does not work exactly? Can you open your console after Sublime startup and see if the AutoHotkey package is being loaded or if there is any error? The highlighting will only show up if you open a .ahk file. Paste your contents of your console after Sublime startup.

**Comment by joedf** [comment]
Stale issue status, and verified it works with v1.7.6 using Package Control with Sublime Text 3.2.2 (3211).
